default: &default
  adapter: postgresql
  encoding: UTF8
  host:     <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  template: template_base
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: bugmark_development

test:
  <<: *default
  database: bugmark_test

production:
  <<: *default
  database: bugmark_production
